{
 "title": "IBM Flashsystem Node Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "spectrum_nodestats_vdisk_w_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_w_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_w_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_w_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_w_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_w_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_r_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_r_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_r_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_r_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_r_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_r_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_sas_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "spectrum_nodestats_sas_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_sas_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "spectrum_nodestats_sas_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_mdisk_w_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "spectrum_nodestats_mdisk_w_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_mdisk_w_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "spectrum_nodestats_mdisk_w_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_mdisk_w_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "spectrum_nodestats_mdisk_w_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_mdisk_r_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "spectrum_nodestats_mdisk_r_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_mdisk_r_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "expr": "spectrum_nodestats_mdisk_r_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_mdisk_r_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "spectrum_nodestats_mdisk_r_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_mdisk_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "expr": "spectrum_nodestats_mdisk_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_iser_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "expr": "spectrum_nodestats_iser_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_iser_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    { "expr": "spectrum_nodestats_iser_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_iscsi_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    { "expr": "spectrum_nodestats_iscsi_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_iscsi_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    { "expr": "spectrum_nodestats_iscsi_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_iplink_comp_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "spectrum_nodestats_iplink_comp_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_nodestats_iplink_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    { "expr": "spectrum_nodestats_iplink_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_mdisk_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    { "expr": "spectrum_nodestats_mdisk_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_mdisk_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    { "expr": "spectrum_nodestats_mdisk_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_iplink_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    { "expr": "spectrum_nodestats_iplink_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_fc_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    { "expr": "spectrum_nodestats_fc_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_fc_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    { "expr": "spectrum_nodestats_fc_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_w_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_w_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_w_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_w_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_r_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_r_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_w_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_w_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_r_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_r_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_write_cache_pc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "spectrum_nodestats_write_cache_pc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_r_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_r_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_total_cache_pc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "expr": "spectrum_nodestats_total_cache_pc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_cpu_pc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "targets": [
    { "expr": "spectrum_nodestats_cpu_pc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_compression_cpu_pc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "spectrum_nodestats_compression_cpu_pc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_nodestats_cloud_down_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "targets": [
    {
     "expr": "spectrum_nodestats_cloud_down_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_nodestats_cloud_up_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "targets": [
    { "expr": "spectrum_nodestats_cloud_up_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_cloud_up_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "targets": [
    { "expr": "spectrum_nodestats_cloud_up_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_cloud_down_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "targets": [
    {
     "expr": "spectrum_nodestats_cloud_down_ms",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}