{
 "title": "IBM Flashsystem overall stats",
 "description": "IBM Flashsystem overall stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "spectrum_system_mdiskgrp_capacity_used_percent",
   "type": "timeseries",
   "description": "The mdiskgrp capacity utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "spectrum_system_mdiskgrp_capacity_used_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_mdiskgrp_free_capacity",
   "type": "timeseries",
   "description": "The amount of MDisk storage that is immediately available. Additionally, reclaimable_capacity can eventually become available",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "spectrum_mdiskgrp_free_capacity",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The mdiskgrp capacity utilization",
   "type": "timeseries",
   "description": "spectrum_system_mdiskgrp_capacity_used_percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "spectrum_system_mdiskgrp_capacity_used_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_mdiskgrp_overallocation",
   "type": "timeseries",
   "description": "The ratio of the virtual_capacity value to the capacity",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "spectrum_mdiskgrp_overallocation",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_mdiskgrp_compression_active",
   "type": "timeseries",
   "description": "Indicates whether any compressed volume copies are in the storage pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "spectrum_mdiskgrp_compression_active",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_mdiskgrp_capacity",
   "type": "timeseries",
   "description": "The total amount of MDisk storage that is assigned to the storage pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "spectrum_mdiskgrp_capacity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_collector_authtoken_renew_failure_total",
   "type": "timeseries",
   "description": "Cumulative count of failed verification of renewed auth token",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "spectrum_collector_authtoken_renew_failure_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_collector_authtoken_renew_success_total",
   "type": "timeseries",
   "description": "Cumulative count of success verification of renewed auth token",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "spectrum_collector_authtoken_renew_success_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_system_total_free_space",
   "type": "timeseries",
   "description": "The sum of mdiskgrp free_capacity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "spectrum_system_total_free_space",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_system_deduplication_capacity_saving",
   "type": "timeseries",
   "description": "The total amount of used capacity that is saved by data deduplication. This saving is before any compression.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "spectrum_system_deduplication_capacity_saving",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_power_w",
   "type": "timeseries",
   "description": "the power that is consumed in watts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "spectrum_systemstats_power_w", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_w_ms",
   "type": "timeseries",
   "description": "The average amount of time in milliseconds that the system takes to respond to write requests to volumes over the sample period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "spectrum_systemstats_vdisk_w_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_r_ms",
   "type": "timeseries",
   "description": "The average amount of time in milliseconds that the system takes to respond to read requests to volumes over the sample period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "spectrum_systemstats_vdisk_r_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_write_cache_pc",
   "type": "timeseries",
   "description": "The percentage of the write cache usage for the node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "spectrum_systemstats_write_cache_pc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_io",
   "type": "timeseries",
   "description": "The average number of I/O operations that are transferred per second for read and write operations to MDisks during the sample period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "spectrum_systemstats_mdisk_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_fc_io",
   "type": "timeseries",
   "description": "The total input/output (I/O) operations that are transferred per seconds for Fibre Channel traffic on the system. This value includes host I/O and any bandwidth that is used for communication within the system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "expr": "spectrum_systemstats_fc_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_drive_io",
   "type": "timeseries",
   "description": "The average number of I/O operations that are transferred per second for read and write operations to drives during the sample period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "spectrum_systemstats_drive_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_iscsi_io",
   "type": "timeseries",
   "description": "The total I/O operations that are transferred per second for iSCSI traffic on the system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "expr": "spectrum_systemstats_iscsi_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_cpu_pc",
   "type": "timeseries",
   "description": "The percentage of allocated CPU capacity that is used for the system.",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 72 },
   "targets": [
    { "expr": "spectrum_systemstats_cpu_pc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_w_ms",
   "type": "timeseries",
   "description": "The average amount of time in milliseconds that the system takes to respond to write requests to volumes over the sample period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_w_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_vdisk_r_ms",
   "type": "timeseries",
   "description": "The average amount of time in milliseconds that the system takes to respond to read requests to volumes over the sample period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_r_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_cpu_pc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {},
    { "expr": "spectrum_nodestats_cpu_pc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_write_cache_pc",
   "type": "timeseries",
   "description": "The percentage of the write cache usage for the node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "spectrum_nodestats_write_cache_pc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_nodestats_drive_io",
   "type": "timeseries",
   "description": "The average number of I/O operations that are transferred per second for read and write operations to drives during the sample period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    { "expr": "spectrum_nodestats_drive_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "\"spectrum_nodestats_vdisk_io\",",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    { "expr": "spectrum_nodestats_vdisk_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_iscsi_io",
   "type": "timeseries",
   "description": "The total I/O operations that are transferred per second for iSCSI traffic on the system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    { "expr": "spectrum_nodestats_iscsi_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_nodestats_fc_io",
   "type": "timeseries",
   "description": "The total input/output (I/O) operations that are transferred per seconds for Fibre Channel traffic on the system. This value includes host I/O and any bandwidth that is used for communication within the system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    { "expr": "spectrum_nodestats_fc_io", "legendFormat": "__auto" }
   ]
  }
 ]
}