{
 "title": "IBM FlashSystem systemstats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "spectrum_systemstats_write_cache_pc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "spectrum_systemstats_write_cache_pc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_w_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "spectrum_systemstats_vdisk_w_io",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_w_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "spectrum_systemstats_vdisk_w_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_r_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "spectrum_systemstats_vdisk_r_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_w_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "spectrum_systemstats_vdisk_w_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "spectrum_systemstats_vdisk_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_r_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "spectrum_systemstats_vdisk_r_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "spectrum_systemstats_vdisk_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_r_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "spectrum_systemstats_vdisk_r_io",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_temp_f",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "spectrum_systemstats_temp_f", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_vdisk_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "spectrum_systemstats_vdisk_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_sas_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "spectrum_systemstats_sas_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_total_cache_pc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "spectrum_systemstats_total_cache_pc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_power_w",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "spectrum_systemstats_power_w", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_temp_c",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "spectrum_systemstats_temp_c", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_w_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "spectrum_systemstats_mdisk_w_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_sas_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "spectrum_systemstats_sas_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_r_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "spectrum_systemstats_mdisk_r_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_w_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "spectrum_systemstats_mdisk_w_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_r_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "spectrum_systemstats_mdisk_r_io",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_w_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "spectrum_systemstats_mdisk_w_io",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    { "expr": "spectrum_systemstats_mdisk_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_r_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "spectrum_systemstats_mdisk_r_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_iser_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    { "expr": "spectrum_systemstats_iser_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    { "expr": "spectrum_systemstats_mdisk_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_iscsi_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    { "expr": "spectrum_systemstats_iscsi_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_mdisk_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    { "expr": "spectrum_systemstats_mdisk_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_iplink_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    { "expr": "spectrum_systemstats_iplink_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_iser_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    { "expr": "spectrum_systemstats_iser_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_iplink_comp_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "spectrum_systemstats_iplink_comp_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_iscsi_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    { "expr": "spectrum_systemstats_iscsi_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_fc_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    { "expr": "spectrum_systemstats_fc_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_iplink_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "targets": [
    { "expr": "spectrum_systemstats_iplink_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_drive_w_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "targets": [
    {
     "expr": "spectrum_systemstats_drive_w_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_fc_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "targets": [
    { "expr": "spectrum_systemstats_fc_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spectrum_systemstats_drive_r_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "spectrum_systemstats_drive_r_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_drive_w_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "spectrum_systemstats_drive_w_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_drive_r_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "expr": "spectrum_systemstats_drive_r_io",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_drive_w_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    {
     "expr": "spectrum_systemstats_drive_w_io",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_drive_r_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "expr": "spectrum_systemstats_drive_r_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_cloud_down_mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "spectrum_systemstats_cloud_down_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_cloud_down_ms ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "spectrum_systemstats_cloud_down_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_cloud_up_ms ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "targets": [
    {
     "expr": "spectrum_systemstats_cloud_up_ms ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spectrum_systemstats_cloud_up_mb ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "targets": [
    {
     "expr": "spectrum_systemstats_cloud_up_mb ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}